export const GET_PETS = "GET_PETS";
export const GET_PET_ID = "GET_PET_ID";
export const GET_ADOPTION_PETS = "GET_ADOPTION_PETS_ADOPTION";
export const GET_LOST_PETS = "GET_LOST_PETS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER_ID = "GET_USER_ID";
export const GET_VETERINARIES = "GET_VETERINARIES";
export const GET_DETAILS_VETERINARIES = "GET_DETAILS_VETERINARIES";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const POST_PET = "POST_PET";
export const UPDATE_PET = "UPDATE_PET";
export const DELETE_PET = "DELETE_PET";
export const POST_USER = "POST_USER";
export const POST_PRODUCT = "POST_PRODUCT";
export const POST_VET = "POST_VET";
export const FILTER_ADOPTION_VALUES = "FILTER_ADOPTION_VALUES";
export const FILTER_BY_SEARCH_AREA = "FILTER_BY_SEARCH_AREA";
export const SHOP_SEARCH_INPUT_NAME = "SHOP_SEARCH_INPUT_NAME";
export const SHOP_FILTER_VALUE = "SHOP_FILTER_VALUE";
export const NEXT_PAGE = "NEXT_PAGE"; // se pueden sacar
export const PREV_PAGE = "PREV_PAGE"; // se pueden sacar
export const ACTUAL_PAGE = "ACTUAL_PAGE"; // se pueden sacar
export const SET_STATUS_USER = "SET_STATUS_USER";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_USER = "UPDATE_USER";
export const MODIFY_PRODUCT = "MODIFY_PRODUCT";
export const OUT_OF_STOCK = "OUT_OF_STOCK";
export const SET_IMAGE = "SET_IMAGE";
